services:  
  whatsapp_api:
    image: atendai/evolution-api:latest
    networks:
      - traefik_public
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    environment:
      CONFIG_SESSION_PHONE_CLIENT: ${CONFIG_SESSION_PHONE_CLIENT}
      AUTHENTICATION_TYPE: ${AUTHENTICATION_TYPE}
      AUTHENTICATION_API_KEY: ${AUTHENTICATION_API_KEY}
      SERVER_URL: ${SERVER_URL}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    
networks:
  traefik_public:
    external: false

volumes:
  evolution_instances:
  evolution_store: